version : '3.8'
services:
  mysql:
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: trading
      MYSQL_PASSWORD: password
      MYSQL_USER: user
    ports:
      - "3306:3306"